dist: xenial

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-amazonlinux CHEF_VERSION=13.0.118
  - INSTANCE=default-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=default-ubuntu-1604 CHEF_VERSION=13.0.118
  - INSTANCE=default-ubuntu-1804 CHEF_VERSION=13.0.118
  - INSTANCE=default-debian-8 CHEF_VERSION=13.0.118
  - INSTANCE=default-debian-9 CHEF_VERSION=13.0.118
  - INSTANCE=default-centos-6 CHEF_VERSION=13.0.118
  - INSTANCE=default-centos-7 CHEF_VERSION=13.0.118
  - INSTANCE=default-amazonlinux
  - INSTANCE=default-amazonlinux-2
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
